### ISSUE TITLE
NUGET_API_KEY isn't honored

### ISSUE THREAD

**Issue by dbxt** [sunsided/docker-nuget#2]
I tried a number of variations on API keys and none of them seemed to work.  It wasn't until I logged into the container interactively that I was able to cat the inc/config.php and see the key actually being used by the server.  

In the dockerfile I can see you're generating a random key here:

```
RUN echo $(date +%s | sha256sum | base64 | head -c 32; echo) > $APP_BASE/.api-key && \
    echo "Auto-Generated NuGet API key: $(cat $APP_BASE/.api-key)" && \
    sed -i $APP_BASE/inc/config.php -e "s/ChangeThisKey/$(cat $APP_BASE/.api-key)/"
```

...but there's nothing in there about using the param passed in.  When I used the randomly generated key I was able to push packages successfully.  My fear is that every time I recreate the container, my API key is going to change and I'll have to `docker exec -it` into the container to get it.  HEre's my compose config:

```
nuget:
  image: sunside/simple-nuget-server
  restart: always
  environment:
    - NUGET_API_KEY:monkey
  ports:
    - "6040:80"
  volumes:
    - /vm/nuget/packages:/var/www/packagefiles
    - /vm/nuget/db:/var/www/db
```

Maybe I'm missing something?

In any case, thanks for posting this image.
