### ISSUE TITLE
Only Deletes allowed

### ISSUE THREAD

**Issue by patrickfraley** [sunsided/docker-nuget#7]
Hi,

I setup a docker server as the documentation describes, I can also push nuget packages into the server and see them on the filesystem /srv/www/packagesfiles but when I try to run

dotnet add package -s http://sulv082:8088/ drk.crm.api.common

it can not find the package.  I also tried

dotnet add package -s http://sulv082:8088/index.php drk.crm.api.common

but then I get the "Only deletes allowed" message.

Where did I mess up?  Any help would be appreciated :)

Best regards

**Comment by rolfwessels** [comment]
I'm having the same issue.

This is my docker compose setup

```
nugetserver:
    container_name: "nugetserver"
    image: "sunside/simple-nuget-server"
    restart: unless-stopped
    environment:
      NUGET_API_KEY: "{{ nuget_api_key }}"
      BASE_URL: "https://nuget.{{ mon_url }}"
    volumes:
      - /data/nuget/database:/var/www/db
      - /data/nuget/packages:/var/www/packagefiles
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nuget.{{ mon_url }}"
```

But when I go to the site the XML says

```
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="http://nuget.xxxxxxxxxxxxxx.com//">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
```

The base should be 'https://nuget.xxxxxxxxxxxxxx.com/' and not `http://nuget.xxxxxxxxxxxxxx.com//`.
It seems to be the double slash at the end that is breaking the request.

Nuget tries to resolve it to
Resolved actions to install package 'xxxxxxxxxx.5.1.0.47-develop'
`  GET http://nuget.xxxxxxxxxxxxxx.com//download/xxxxxxxxxx/5.1.0.47-develop`

When I call that directly I only a response `Only DELETEs allowed here`. If I remove the double slash it works.
