### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by KevinBurton** [sunsided/docker-nuget#8]
I have a docker-compose.yml that looks like
```
version: '3.4'

services:
  nuget-server:
    image: sunside/simple-nuget-server
    environment:
      - NUGET_API_KEY=823281825
      - BASE_URL=/nuget
    volumes:
      - nuget-database:/var/www/db
      - nuget-packages:/var/www/packagefiles
    ports:
      - 56000:5000

volumes:
  nuget-database:  
  nuget-packages:

```
When I issue the command `nuget push -Source http://localhost:56000/nuget -ApiKey 823281825 coremodels/1.0.0/coremodels.1.0.0.nupkg` I get
```
Pushing coremodels.1.0.0.nupkg to 'http://localhost:56000/nuget'...
  PUT http://localhost:56000/nuget/
An error was encountered when fetching 'PUT http://localhost:56000/nuget/'. The request will now be retried.
The HTTP request to 'PUT http://localhost:56000/nuget/' has timed out after 300000ms.
A task was canceled.
  Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.
```
I cannot see that I have started up the container or called `nuget` incorrectly. Can you see the cause of the timeout?
